### ISSUE TITLE
JSON as default accept

### ISSUE THREAD

**Issue by danielwertheim** [DuendeArchive/IdentityModel.PCL#16]
Seems to me like `UserInfoClient` is missing requesting with `Accept: application/json`. E.g.:

```
_client.DefaultRequestHeaders.Accept.Add(
    new MediaTypeWithQualityHeaderValue("application/json"));
```

You are at least expecting to parse the result as JSON: https://github.com/IdentityModel/IdentityModel/blob/master/source/IdentityModel.Shared/Client/UserInfoResponse.cs#L32

And when using against a host, with e.g. custom middleware for handling errors, you want to inspect the requests `Accept` header to e.g. return HTML,JSON, Empty....

Now, I understand that I can inject a custom handler and, handle it in the `SendAsync` but again, since you parse the response as JSON, might as well add the header.

**Comment by leastprivilege** [comment]
PR?

— 
cheers
Dominick Baier

On 2 October 2015 at 10:24:49, Daniel Wertheim (notifications@github.com) wrote:

Seems to me like UserInfoClient is missing requesting with Accept: application/json. E.g.:

_client.DefaultRequestHeaders.Accept.Add(
    new MediaTypeWithQualityHeaderValue("application/json"));

You are at least expecting to parse the result as JSON: https://github.com/IdentityModel/IdentityModel/blob/master/source/IdentityModel.Shared/Client/UserInfoResponse.cs#L32

And when using against a host, with e.g. custom middleware for handling errors, you want to inspect the requests Accept header to e.g. return HTML,JSON, Empty....

Now, I understand that I can inject a custom handler and, handle it in the SendAsync but again, since you parse the response as JSON, might as well add the header.

**Comment by danielwertheim** [comment]
Sure

**Comment by leastprivilege** [comment]
I mean the spec says that the userinfo endpoint must return JSON regardless of the accept header. You probably also wanna clear the accept header collection first since this is the only valid response media type.

**Comment by leastprivilege** [comment]
looks good? https://github.com/IdentityModel/IdentityModel/commit/c727fa2807b6b512b15ab85cacf7fe9d80a99a78

**Comment by danielwertheim** [comment]
Yes. Commented in the commit.

**Comment by danielwertheim** [comment]
Any news of when this will be out?

**Comment by leastprivilege** [comment]
already done 1.2.0 IIRC
